### ISSUE TITLE
json is not returning from api 

### ISSUE THREAD

**Issue by sajcics** [cirquity/cirquity-explorer#2]
Hi.
I have problem with this line of code https://github.com/cirquity/cirquity-explorer/blob/16a43f54f803f43b590518a585d68d4d39839183/api/utils.php#L32 when I request supply from this url:https://explorer.cirquity.com/api/supply. Probably there is missing json_encode before sending result to be in valid format.

Issue: on frontend result from backend can not be parsed and result from api is not json;
expected: to have json structure (as result of endpoint: https://explorer.cirquity.com/api/supply)

**Comment by deeterd** [comment]
Hi, I fixed the request from AJAX to return the correct JSON Encoded contents.

You can review it here: https://github.com/cirquity/cirquity-explorer/commit/d514bff2ca616a53bd698e29e98f26187408e26f

**Comment by sajcics** [comment]
@deeterd thanks, but I still do not get back response's type json instead I got document.
https://explorer.cirquity.com/api/supply please check 
![image](https://user-images.githubusercontent.com/16606051/92919277-7febf880-f430-11ea-9d6a-d73a3197ec2a.png)

**Comment by deeterd** [comment]
Sorry for the late reply.
It'll be activated if you request using AJAX with "X_REQUESTED_WITH". It will always be on that format if you view it on browser.
